# Role table and Betweenness table

In [1]:
import pickle
import pandas as pd
import networkx as nx

In [2]:
l_g_file=['carnival_tourist','no_carnival_tourist','carnival_residents','no_carnival_residents']

## Role table

In [3]:
list_rol=list()
for i in l_g_file:
    with open('../data/'+i+'_rol.pickle', 'rb') as handle:
        list_rol.append( pickle.load(handle))
        
df = pd.DataFrame({
    l_g_file[0]: pd.Series(list_rol[0]),
    l_g_file[1]: pd.Series(list_rol[1]),
    l_g_file[2]: pd.Series(list_rol[2]),
    l_g_file[3]: pd.Series(list_rol[3])
})
df

,carnival_tourist,no_carnival_tourist,carnival_residents,no_carnival_residents
Aeroporto,R3 Non-hub connectors,R3 Non-hub connectors,R2 Peripheral,R3 Non-hub connectors
Alberoni Faro Rocchetta N,R2 Peripheral,R2 Peripheral,NaN,R2 Peripheral
Arsenale DX,R7 Kinless hubs,R7 Kinless hubs,R3 Non-hub connectors,R3 Non-hub connectors
Bacini - Arsenale Nord,R7 Kinless hubs,R4 Non-hub kinless,R6 Connector hubs,R2 Peripheral
Burano DX per Treporti,R6 Connector hubs,R6 Connector hubs,R6 Connector hubs,R6 Connector hubs
...,...,...,...,...
Tre Archi,R7 Kinless hubs,R7 Kinless hubs,R3 Non-hub connectors,R3 Non-hub connectors
Treporti,R2 Peripheral,R2 Peripheral,R2 Peripheral,R2 Peripheral
Tronchetto 'B' SX,R3 Non-hub connectors,R4 Non-hub kinless,R3 Non-hub connectors,R3 Non-hub connectors
Zattere SX,R3 Non-hub connectors,R7 Kinless hubs,R6 Connector hubs,R6 Connector hubs
Zitelle SX,R3 Non-hub connectors,R7 Kinless hubs,R3 Non-hub connectors,R3 Non-hub connectors

## Betweenness table

In [4]:
list_btw=list()
for i in l_g_file:
    G=nx.read_graphml('../data/'+i+'.graphml')
    
for i in G.nodes():
    btw=nx.betweenness_centrality(G, k=None, normalized=True, weight=None, endpoints=False, seed=None)
    list_btw.append(btw)
df = pd.DataFrame({
    l_g_file[0]: pd.Series(list_btw[0]),
    l_g_file[1]: pd.Series(list_btw[1]),
    l_g_file[2]: pd.Series(list_btw[2]),
    l_g_file[3]: pd.Series(list_btw[3])
})
df

,carnival_tourist,no_carnival_tourist,carnival_residents,no_carnival_residents
Punta Sabbioni DX,0.012406,0.012406,0.012406,0.012406
"Lido (S.M.E.) ""B""",0.074635,0.074635,0.074635,0.074635
S. Elena DX,0.028332,0.028332,0.028332,0.028332
Giardini Biennale SX,0.010781,0.010781,0.010781,0.010781
Crea,0.000547,0.000547,0.000547,0.000547
...,...,...,...,...
Santa Maria Del Mare,0.000000,0.000000,0.000000,0.000000
Bacini - Arsenale Nord,0.000634,0.000634,0.000634,0.000634
S. Pietro di Castello,0.001875,0.001875,0.001875,0.001875
P.le Roma (Hotel S. Chiar,0.072522,0.072522,0.072522,0.072522
Piazzale Roma,0.014345,0.014345,0.014345,0.014345